### PR TITLE
generating dummy data to seed db

### PR DESCRIPTION
**Pull request by kbsjsn**
[ops] added script "npm seed"
[ops] added module dependencies 
[feat] added schema for db
[feat] added functionality to generate and seed random dummy data

### CODE REVIEW

**Review by impromptuu — COMMENTED** [review]
Looks good.  Still need to implement your server path to get a set of recommended items for a specific itemId and make an example gist and post it to the google docs deliverables step 1 section.

**Comment by impromptuu** [comment]
Also name your branches based on the feature you are currently implementing 👍

**Comment by kbsjsn** [comment]
Here's the result of an API call by id for one recommended item
https://gist.github.com/kbsjsn/a59d1ad1e047f712cf4f2e8baf5c88cf

Here's the result for a call for all recommended items
https://gist.github.com/kbsjsn/b3fb7f98ce56d1707cba37c04861a71f

**Review by kataing — COMMENTED** [review]
Looks good! If you get a chance, I'd recommend trying to refactor to match the airbnb style guide.

**Pull request merged**
